/*
Copyright 2021 The Kubermatic Kubernetes Platform contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	registrymanv1alpha1 "github.com/kubermatic-labs/registryman/pkg/apis/registryman/v1alpha1"
	versioned "github.com/kubermatic-labs/registryman/pkg/apis/registryman/v1alpha1/clientset/versioned"
	internalinterfaces "github.com/kubermatic-labs/registryman/pkg/apis/registryman/v1alpha1/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubermatic-labs/registryman/pkg/apis/registryman/v1alpha1/listers/registryman/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScannerInformer provides access to a shared informer and lister for
// Scanners.
type ScannerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ScannerLister
}

type scannerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScannerInformer constructs a new informer for Scanner type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScannerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScannerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScannerInformer constructs a new informer for Scanner type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScannerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RegistrymanV1alpha1().Scanners(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RegistrymanV1alpha1().Scanners(namespace).Watch(context.TODO(), options)
			},
		},
		&registrymanv1alpha1.Scanner{},
		resyncPeriod,
		indexers,
	)
}

func (f *scannerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScannerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scannerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&registrymanv1alpha1.Scanner{}, f.defaultInformer)
}

func (f *scannerInformer) Lister() v1alpha1.ScannerLister {
	return v1alpha1.NewScannerLister(f.Informer().GetIndexer())
}
