apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: registryman-webhook
rules:
- apiGroups:
  - registryman.kubermatic.com
  resources:
  - registries
  - projects
  - scanners
  verbs:
  - list
