apiVersion: v1
kind: Service
metadata:
  labels:
    app: registryman-webhook
  name: registryman-webhook
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: registryman-webhook
  type: ClusterIP
