apiVersion: apps/v1
kind: Deployment
metadata:
  name: registryman-webhook
spec:
  template:
    spec:
      containers:
      - name: registryman
        args: ["webhook", "--namespace", "default", "-v"]

