apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: registryman-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registryman-webhook
subjects:
- kind: ServiceAccount
  name: registryman-webhook
  namespace: default
