apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registryman-webhook
  name: registryman-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registryman-webhook
  template:
    metadata:
      labels:
        app: registryman-webhook
    spec:
      serviceAccountName: registryman-webhook
      containers:
      - image: registryman
        name: registryman
        args: ["webhook", "--namespace", "default" ]
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: cert
          mountPath: /tls
      volumes:
      - name: cert
        secret:
          secretName: registryman-webhook-cert

