apiVersion: registryman.kubermatic.com/v1alpha1
kind: Project
metadata:
  name: global-project
spec:
  type: Global
  members:
  - name: alpha
    role: Maintainer
  - name: beta
    role: Developer
  - name: developers
    type: Group
    role: Developer
    dn: cn=Developers,ou=users,dc=example,dc=com
