apiVersion: registryman.kubermatic.com/v1alpha1
kind: Project
metadata:
  name: local-project
  namespace: default
spec:
  type: Local
  localRegistries:
  - local-reg
  members:
  - name: alpha
    role: Maintainer
  - name: beta
    role: Developer
  scanner: anchore-scanner
  trigger:
    type: cron
    schedule: "*/15 * * * *"
