apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: registryman-webhook
  name: registryman-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registryman-webhook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registryman-webhook
    spec:
      serviceAccountName: registryman-webhook
      containers:
      - image: registryman
        name: registryman
        args: ["webhook"]
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: ca
          mountPath: /tls
      volumes:
      - name: ca
        secret:
          secretName: registryman-webhook-ca

